services:
  postgres:
    image: postgres:16
    container_name: hint1k_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: financedb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  finance:
    build:
      context: ./Task2
      dockerfile: Task2/Dockerfile
    container_name: hint1k_finance
    env_file:
      - Task2/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8080" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: