app:
  db:
    url: "jdbc:postgresql://postgres:5432/financedb"
server:
  port: 8080
logging:
  level:
    root: INFO
    com.demo.finance: INFO
    com.demo.finance.app.config: INFO
    com.demo.finance.in.controller: INFO
    com.demo.finance.out.repository: WARN
    com.demo.finance.domain.model: ERROR
    com.demo.finance.exception: ERROR
    com.demo.finance.in.filter: INFO
    liquibase: WARN
    org.springframework.web: WARN
    org.springdoc: WARN
    org.springdoc.core: WARN
    org.springdoc.api: WARN
    org.springdoc.webmvc: WARN
    org.eclipse.jetty: WARN
    org.eclipse.jetty.server: WARN
    org.eclipse.jetty.client: WARN
  file:
    name: /app/logs/app.log
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%-5level","class":"%logger{36}","message":"%msg"}%n'
    file: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%-5level","class":"%logger{36}","message":"%msg"}%n'
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
logging-aspect:
  slow-method-threshold-ms: 500